# Reglas de juego de mesa favorito con múltiples prints
print("Reglas de Wingspan")
print("1. Cada jugador tiene un tablero con tres hábitats: bosque, pradera y humedal")
print("2. El jugador deve elegir entre 5 aves al inicio del juego, y 5 alimentos") 
print("   hasta tener 5 en total entre aves y alimentos")
print("3. Cada jugador debe elegir una entre 3 cartas de bonificación")
print("4. En tu turno puedes: jugar un ave, ganar alimento, poner huevos o robar cartas")
print("5. Para jugar un ave debes pagar su costo en alimento, huevos y colocarlo en el")
print("   hábitat correspondiente")
print("6. No puedes jugar un ave si no tienes espacio en el hábitat")
print("7. Para ganar alimento debes usar dados especiales para obtener comida")
print("8. Cada acción activa habilidades de aves que ya hayas jugado en ese hábitat")
print("9. Al final de cada ronda se evalúan los objetivos comunes")
print("10. Al final del juego se suman los puntos de aves, objetivos, bonificaciones, ")
print("    huevos, alimentos almacenados y cartas debajo de otras aves")
print("11. Gana el jugador con más puntos")