# Conversacion entre un gato y una persona
print("Humano: Hola señor gato, ¿cómo estás?")
print("Gato: Hola humano, estoy bien. ¿Y tú?, digo miau miau miau")
print("Humano: Oooh, no sabía que los gatos hablaran")
print("Gato: Miau miau miau ?")
print("Humano: Ya veo que no hablas, solo maullas")
print("yo que queria darle un premio a un gato que hablara")
print("Gato: no caere en tu trampa, humano")
print("Humano: ¿Qué trampa?")
print("Gato: La de darme un premio, no soy un gato tonto")
print("Humano: ...")
print("Gato: ...")
print("Humano: Quieres un poco de comida?")
print("Gato: Si, muchas gracias humano")
print("Humano: Me llamo Laurent")
print("Gato: Gracias Laurent, dime Arthur")
print("Humano: Bueno, hasta mañana Arthur")
print("Gato: Hasta mañana Laurent")